remote_theme: tomjoht/documentation-theme-jekyll@gh-pages

#enable local builds using remote theme
plugins:
  - jekyll-remote-theme

repository: makerfaireorlando/maker-event-playbook

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Maker Faire Orlando Playbook
# this appears on the top navigation bar next to the home button

site_title: Maker Faire Orlando Playbook
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: The Maker Effect Foundation
# this appears in the footer

github_editme_path: makerfaireorlando/maker-event-playbook/blob/master/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

feedback_subject_line: Maker Faire Orlando Playbook

feedback_email: makers@makerfaireorlando.com
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  events:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: home_sidebar
      topnav: topnav


# these are defaults used for the frontmatter for these file types


sidebars:
- home_sidebar


exclude:
- README

description: "A guide for producing Maker Faire Orlando, created by those who have made it possible in the past."
# the description is used in the feed.xml file

theme: jekyll-theme-time-machine

baseurl:

url: https://www.makereventplaybook.org

# set timezone
timezone: America/New_York
