remote_theme: tomjoht/documentation-theme-jekyll@gh-pages

repository: nationofmakers/maker-event-playbook

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Maker Event Playbook
# this appears on the top navigation bar next to the home button

site_title: Maker Event Playbook
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Nation of Makers
# this appears in the footer


