remote_theme: tomjoht/documentation-theme-jekyll@gh-pages

repository: nationofmakers/maker-event-playbook

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Maker Event Playbook
# this appears on the top navigation bar next to the home button

site_title: Maker Event Playbook
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Nation of Makers
# this appears in the footer

github_editme_path: nationofmakers/maker-event-playbook/blob/master/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

feedback_subject_line: Maker Event Playbook

feedback_email: ian.cole@themakereffect.org
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 

sidebars:
- home_sidebar
- large_event_sidebar
- makerspace_event_sidebar

description: "A guide for producing Maker Events, brought to you by the community of maker event producers within Nation of Makers."
# the description is used in the feed.xml file
